import streamlit as st
import os
import pandas as pd
from datetime import datetime
from components.ui_elements import PrakritUI

# --- 0. FORCE ECO-LUXURY UI ---
PrakritUI.inject_pro_css()
PrakritUI.apply_glass_forms()

# Ensure Pathway input directory exists for the AI Engine
os.makedirs("data/input", exist_ok=True)

# Establish connection
cursor = db.cursor()

st.title("🛡️ NGO Real-Time Verification Portal")
st.caption(f"Welcome, {u['username']} | Validating the Ecosystem via Pathway AI")

tab_cl, tab_aud = st.tabs(["📋 Active Stream & Deploy", "✅ Live AI Sync & History"])

# ==========================================
# TAB 1: CLAIMING & DEPLOYING TO PATHWAY
# ==========================================
with tab_cl:
    st.subheader("Bookings Requiring Verification")
    # Fetch Paid & Confirmed bookings not yet audited
    cursor.execute("""SELECT *
                      FROM bookings
                      WHERE status = 'Paid & Confirmed'
                        AND (audit_status IS NULL OR audit_status = '')""")
    active = cursor.fetchall()

    if active:
        for b in active:
            # Replaced the buggy expander with a clean container
            with st.container(border=True): 
                st.markdown(f"#### 📦 Audit Order {b[1]} - {b[3]}")
                st.write(f"**Event Details:** {b[6]}")
                if st.button(f"Claim Audit for {b[1]}", key=f"cl_{b[1]}", use_container_width=True):
                    cursor.execute(
                        "UPDATE bookings SET audit_status = 'Claimed', auditor_name = ? WHERE booking_id = ?",
                        (u['username'], b[1]))
                    db.commit()
                    st.rerun()
    else:
        st.info("No active bookings waiting for verification.")

    # --- SECTION 2: PATHWAY DATA INGESTION ---
    st.divider()
    cursor.execute("SELECT * FROM bookings WHERE auditor_name = ? AND audit_status = 'Claimed'", (u['username'],))
    claims = cursor.fetchall()

    if claims:
        st.subheader("🚀 Deploy to Pathway Engine")
        
        # Wrapped in a glass form for aesthetic consistency
        with st.form("deploy_pathway_form"):
            sel_b = st.selectbox("Select Booking to Audit", [c[1] for c in claims])
            report = st.file_uploader(f"Upload Sustainability Proof for {sel_b}", type=['txt', 'pdf'])

            if st.form_submit_button("Trigger Live Pathway Audit"):
                if report:
                    # Save file to the 'Hot Folder' Pathway is watching (main.py)
                    # We rename the file with the booking ID so Pathway results can be mapped back
                    save_path = f"data/input/{sel_b}_report.txt"
                    with open(save_path, "wb") as f:
                        f.write(report.getbuffer())

                    # Update local status to reflect it's being processed
                    cursor.execute("UPDATE bookings SET audit_status = 'In Pathway Stream' WHERE booking_id = ?", (sel_b,))
                    db.commit()
                    st.success(f"Audit {sel_b} is now being processed by the Pathway LiveAI engine!")
                    st.rerun()
                else:
                    st.warning("Please upload a report file to begin.")

# ==========================================
# TAB 2: LIVE FEED FROM PATHWAY & DB SYNC
# ==========================================
with tab_aud:
    # --- SECTION 3: LIVE FEED FROM PATHWAY ---
    st.subheader("📈 Live Pathway Analysis Feed")
    results_path = "data/pathway_results.csv"

    if os.path.exists(results_path):
        # Pathway writes results here in real-time
        pathway_df = pd.read_csv(results_path)
        
        if not pathway_df.empty:
            # 1. FIX DUPLICATES: Keep only the latest result for each unique report file
            display_df = pathway_df.sort_values('processed_at', ascending=False).drop_duplicates('filename')
            
            # 2. FIX "BLACK" UI: Force high-contrast styling so it's readable
            # This ensures the table looks clean regardless of system dark mode
            st.dataframe(
                display_df.style.set_properties(**{
                    'background-color': '#ffffff',
                    'color': '#1b1b1b',
                    'border-color': '#2e7d32'
                }),
                use_container_width=True
            )
        else:
            st.info("Pathway stream is active but no reports have been processed yet.")


        if st.button("🔄 Sync Pathway Scores to Ecosystem"):
            for _, row in pathway_df.iterrows():
                # Extract booking ID from filename (e.g., data/input/B123_report.txt -> B123)
                filename = os.path.basename(row['filename'])
                b_id = filename.split("_")[0]
                ai_score = float(row['ai_score'])

                # Update SQLite with results generated by Pathway
                is_eco = ai_score >= 7.5
                now = datetime.now().strftime("%Y-%m-%d %H:%M")

                # 1. Update Booking
                cursor.execute("""UPDATE bookings
                                  SET audit_score  = ?,
                                      audit_status = 'Verified',
                                      status       = ?
                                  WHERE booking_id = ?""",
                               (ai_score, 'Verified Eco-Friendly' if is_eco else 'Audit Failed', b_id))

                if is_eco:
                    # 2. Credit Organizer +100 Mudra (using data from the booking)
                    cursor.execute("SELECT organizer FROM bookings WHERE booking_id = ?", (b_id,))
                    org_row = cursor.fetchone()
                    if org_row:
                        org_user = org_row[0]
                        cursor.execute("UPDATE users SET wallet = wallet + 100 WHERE username = ?", (org_user,))
                        cursor.execute(
                            "INSERT INTO transactions (username, amount, type, reason, timestamp) VALUES (?,?,?,?,?)",
                            (org_user, 100, "Credit", f"Verified Audit: {b_id}", now))

                        # 3. Update Organizer Average Score
                        cursor.execute("SELECT AVG(audit_score) FROM bookings WHERE organizer = ?", (org_user,))
                        avg_s = cursor.fetchone()[0]
                        cursor.execute("UPDATE users SET score = ?, audited = 1 WHERE username = ?",
                                       (round(avg_s, 1), org_user))

            db.commit()
            st.success("Pathway data synced successfully!")
            st.rerun()
    else:
        st.info("Waiting for first live pulse from Pathway engine...")